### ISSUE TITLE
imap messes with <Space> leader

### ISSUE THREAD

**Issue by imain** [cwoac/nvim#33]
I'm liking nvim!  However, when trying to use it I noticed right away that you have a inoremap using the <leader>.  I have my leader as <Space> so it is constantly trying to execute searches etc.  It would be nice to have a way to disable the automatic leader assignment or maybe make it so you could at least disable the imaps.

Thanks!!

**Comment by weaksauce** [comment]
Agreed. this is kind of a big deal for people that use space for a leader. (I am one as well)

**Comment by cwoac** [comment]
Okay, I've added an option to disable it on interactive mode (if you disable it on normal mode, it pretty much breaks the program).
