### ISSUE TITLE
Empty extension (no "." in file name)  of files is not supported

### ISSUE THREAD

**Issue by granin** [cwoac/nvim#35]
I need Empty extension of files because I use SoyWiki ( https://github.com/danchoi/soywiki ) and it works only with empty extension.
When I set it like this:
```
let g:NVIM_extension = ''
```
and delete files or update index with "python nvimdb.rebuild_database()" 

I get error: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mikhailgranin/bin/dotfiles/vim/bundle/nvim/python/nvim.py", line
58, in rebuild_database
    self.update_file(f)
  File "/Users/mikhailgranin/bin/dotfiles/vim/bundle/nvim/python/nvim.py", line
64, in update_file
    fh = open( filename, 'r' )
IOError: [Errno 21] Is a directory: 'nvimi'
```
in general I see that database folder is included in indexing, I tried changing the directory used for the note database replacing in : 
```
let g:NVIM_database  = '.nvim'
```
'.nvim' with every possible option but it's still giving same error. 

Please update code so that empty  extension (no "." in file name)  of files is working.

**Comment by cwoac** [comment]
Hmmm. Will have a look into it.

**Comment by granin** [comment]
Thank you @cwoac ! I've already forked your project and got some experiments on it (really minor ones), so if you have any ideas on how I can resolve this issue myself, let me know.

**Comment by cwoac** [comment]
Okay,  so I'm pretty sure I've fixed it, but I'm not in a position to test it properly right now (long story).

I figure it's probably worth putting the code up here so you can have a look at it if you want while I kick my system into shape.

**Comment by granin** [comment]
Thank you! Will test it and let you know how it works for me.

**Comment by granin** [comment]
It works for starting from scratch but when I'm trying to import old notes it's broken:

```
:python nvimdb.rebuild_database() always returns 
```
returns

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mikhailgranin/bin/dotfiles/vim/bundle/nvim/python/nvim.py", line
58, in rebuild_database
    self.update_file(f)
  File "/Users/mikhailgranin/bin/dotfiles/vim/bundle/nvim/python/nvim.py", line
64, in update_file
    fh = open( filename, 'r' )
IOError: [Errno 21] Is a directory: '.nvimi'
```

**Comment by cwoac** [comment]
ack; I forgot we parse the notes in multiple places. Easy to fix.

**Comment by cwoac** [comment]
Sorry, I should have been clearer - I've checked my (suggested) fix into a new branch `empty_extension` - see 1e359100d98c4cbd40001699e6e2dc333229c6ce. From your error message you are still on `master`

**Comment by granin** [comment]
ok! I’ll check it.

**Comment by cwoac** [comment]
Any luck?

**Comment by cwoac** [comment]
I've got my development environment sorted and have checked (and fixed) the issue. Hope it helps.
