### ISSUE TITLE
Error on opening

### ISSUE THREAD

**Issue by AmaruCoder** [cwoac/nvim#36]
Thank you for putting this plugin together. After installation, when I try to invoke the plugin (with <leader>F5), I get the following error:

"_nvim" [New File]
Error detected while processing function NVIM_init..<SNR>62_DefPython:
line  320:
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named xapian

Any ideas of what might be wrong.

**Comment by cwoac** [comment]
You need the xapian bindings for python installed (specifically for python 2) - which package gives this is dependent upon which distro you are using.

**Comment by AmaruCoder** [comment]
Thank you.
