### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by srccon** [cwoac/nvim#37]
I'm running debian wheezy. 

I hit this on loading
````
"_nvim" [New File]
Error detected while processing function NVIM_init..<SNR>11_DefPython:
line    2:
E319: Sorry, the command is not available in this version: pyfile /home/bang/.vim/bundle/nv
im/python/nvim.py
````
I really hope to get this working. I love the idea. Thanks!

**Comment by cwoac** [comment]
This means your version of vim has been compiled without python (or possibly without the right version). Try installing `vim-full`

**Comment by srccon** [comment]
`vim-full` did not work but `vim-python` did. Thanks so much for your help. I was a little confused by what you meant by xapian and python, I was looking for python bindings for xapian.  I love how it works!

**Comment by srccon** [comment]
Sorry, I screwed that up. Like you said, I need the full vim with python bindings, on debian wheezy, to install python bindings it requires installing something `vim-gtk', one cannot install `vim-python' directly. 

Thanks for your help.
