### ISSUE TITLE
Lurving this plugin but was wondering if development has gone fallow...

### ISSUE THREAD

**Issue by wakatara** [cwoac/nvim#42]
Hey there,

Just wanted to say how impressed I've been with nvim. I find it a surprisingly great replacement for NVAlt and other things but was just curious, since it appears it's gone fallow, what you ended up replacing it with.

Just wanted to say thanks for making this. Despite its warts, it's a great vim plugin!

**Comment by cwoac** [comment]
Nothing, actually. It's not so much fallow as (that rare thing in an OS project), done.

Well, there are a couple of things on the todo list, but nothing that actually needs doing, so.
