### ISSUE TITLE
DatabaseLockError: Unable to get write lock on .nvim: already locked

### ISSUE THREAD

**Issue by hgvhgv** [cwoac/nvim#44]
Hi,

Nvim is working great for me, but I'm having to rebuild the Xapian database every time I launch. When I try to reload the db with `:python nvimdb.reload_database()` I get the below error. It's possible this is related to permissions/user issue I have on my setup, stemming from an attempt to share a drive between mac osx and arch linux. But after trying to chase that down for a while, I'm sort of stuck, hence coming here. 

This happens across reboots. The error only shows up when I call `:python nvimdb.reload_database()` myself; upon launching nvim either from the script or in vim, it just loads with an empty databse and `strace` doesn't show any such error. Maybe I've misread the nvim.py file in thinking `reload_database` runs at each init?

Thanks for such a great program!

Edit: quick clarification. I have nvim installed as "nvel" in my neovim plugins folder, hence the possibly confusing use of "nvim" and "nvel" below.

```
Error detected while processing function provider#python#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hgv/.local/share/nvim/plugged/nvel/python/nvim.py", line 26, in reload_database
    self.db = xapian.WritableDatabase( self.database,xapian.DB_CREATE_OR_OPEN )
  File "/usr/lib/python2.7/site-packages/xapian/__init__.py", line 4399, in __init__
    _xapian.WritableDatabase_swiginit(self,_xapian.new_WritableDatabase(*args))
DatabaseLockError: Unable to get write lock on .nvim: already locked
```

**Comment by cwoac** [comment]
hmmm. So yes, `reload_database` does get called  on start. The error indicates that it thinks another running process currently owns the .nvim directory, it could be permissions, but unlikely.

Does this occur in a fresh directory or just the one with your old notes in? if you have a terminal on the directory where the error occurs, what does `ls -lA .nvim` give you?

**Comment by hgvhgv** [comment]
Yes, this occurs in both a fresh directory (tried on both the shared partition I mentioned and on a nonshared one) and the already existing one. And on both, I get (depending on size) the same output on `ls -lA .nvim`, so should be writable by me:

```
total 8500
-rw-r--r-- 1 hgv hgv       0 Jan  3 13:17 flintlock
-rw-r--r-- 1 hgv hgv      28 Jan  3 13:17 iamchert
-rw-r--r-- 1 hgv hgv      13 Jan  3 13:17 position.baseA
-rw-r--r-- 1 hgv hgv 3432448 Jan  3 15:28 position.DB
-rw-r--r-- 1 hgv hgv      13 Jan  3 13:17 postlist.baseA
-rw-r--r-- 1 hgv hgv 3457024 Jan  3 15:23 postlist.DB
-rw-r--r-- 1 hgv hgv      13 Jan  3 13:17 record.baseA
-rw-r--r-- 1 hgv hgv   49152 Jan  3 15:28 record.DB
-rw-r--r-- 1 hgv hgv      13 Jan  3 13:17 termlist.baseA
-rw-r--r-- 1 hgv hgv 1744896 Jan  3 15:28 termlist.DB
```

Poking around `xapian` docs hasn't helped me; I don't see the `cat` process or anything related to `fcntl()` on `top` (as mentioned here: <https://getting-started-with-xapian.readthedocs.io/en/latest/advanced/admin_notes.html#single-writer-multiple-reader>).

Just thought to try `lsof` to see if anything else is up. When `nvim` is not running, nothing shows up; once I've opened it via my `nvel` script (but without the database loading or being rebuilt), `lsof | grep .nvim` results in (with results for `nvim` as in `neovim` omitted). Though maybe this isn't helpful as `nvim` is already running. 

```
nvel      6021       hgv  255r      REG                8,5       885     303743 /home/hgv/.local/share/nvim/plugged/nvel/nvim
[. . .]
python2   6025       hgv    7ww     REG                8,5         0     389724 /home/hgv/documents/Details/Data/NotationalVelocity/.nvim/flintlock
python2   6025       hgv    8u      REG                8,5     49152     389731 /home/hgv/documents/Details/Data/NotationalVelocity/.nvim/record.DB
python2   6025       hgv    9u      REG                8,5   1744896     389729 /home/hgv/documents/Details/Data/NotationalVelocity/.nvim/termlist.DB
python2   6025       hgv   10u      REG                8,5   3432448     389733 /home/hgv/documents/Details/Data/NotationalVelocity/.nvim/position.DB
python2   6025       hgv   11u      REG                8,5   3457024     389727 /home/hgv/documents/Details/Data/NotationalVelocity/.nvim/postlist.DB
```

I'm happy to keep digging, as `nvalt` was pretty fundamental to my work life on mac, so `nvim` has been a godsend in switching—would just be nice to not have to rebuild the db everytime (though this hasn't seemed to cause any problems).

**Comment by cwoac** [comment]
rebuilding the db is safe - it is just a cache after all. I wonder if it is (if I understand you correctly) because you are running it under neovim - some difference in the python engines between the two?

**Comment by hgvhgv** [comment]
You are correct and I had wondered about that. Will check in and report back.

**Comment by cwoac** [comment]
Did you get anywhere on this?

**Comment by hgvhgv** [comment]
I actually moved away from using the plugin when I found others that met my needs more specifically (and allowed me to stop troubleshooting this). But thanks for checking in!

**Comment by cwoac** [comment]
Interesting. Which one, out of curiousity?

**Comment by hgvhgv** [comment]
I started using **fzf** in general, which led me to <https://github.com/Alok/notational-fzf-vim>.

**Comment by cwoac** [comment]
Interesting. Thanks for the update.
